added conditions

diff --git a/08-install-mysql b/08-install-mysql
--- a/08-install-mysql
+++ b/08-install-mysql
@@ -9,5 +9,13 @@ then
     echo "ERROR:: please run this script with root access"
     exit 1
 fi    
-
+#it is our responsibility again to check installion is success or not
 yum install git -y
+
+if [ $? -ne 0 ]
+then 
+    echo "installion of mysqllll is error"
+    exit 1  
+else
+    echo "installation of mysql is success"
+if        
